name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default branch isn't main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # SPA fallback so /aboutme, /projects, etc. work on refresh
      - name: Add 404 fallback
        run: node -e "require('fs').copyFileSync('dist/index.html','dist/404.html')"

      # - name: Add SPA fallback
      #   run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.thelylabean.dev   # change if your primary domain is apex
